config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  resources :foods
  resources :publics, only: [:index]
  resources :recipe_foods

  root "publics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 100 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :name
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :recipe_id, presence: true
  validates :food_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success, :messages, :notice, :alert
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :password, :password_confirmation, :email, :image)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :password_confirmation, :email, :current_password, :image)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc).with_attached_image
  end

  def new
    @food = Food.new
  end

  def create
    new_food = Food.new(food_params)
    new_food.user_id = current_user.id

    if new_food.save
      flash.now[:success] = 'Food was successfully created.'
      redirect_to foods_path
    else
      flash.now[:danger] = 'Food was not created because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
      render :new
    end
  end

  def destroy
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc).with_attached_image

    food_to_delete = Food.find(params[:id])
    if food_to_delete.destroy
      flash.now[:success] = 'Food was successfully deleted.'
    else
      flash.now[:danger] = 'Food was not deleted because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
    end
    render :index
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :image)
  end

  private :food_params
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  before_action :authenticate_user!
  def index
    @food_amount = 0
    @total_price = 0
    @recipe_foods = []
    @recipes = current_user.recipes

    @recipes.includes(:recipe_foods).each do |recipe|
      @food_amount += recipe.recipe_foods.count
      @recipe_foods << recipe.recipe_foods
      recipe.recipe_foods.includes(:food).each do |recipe_food|
        @total_price += recipe_food.food.price * recipe_food.quantity
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
  def index
    @recipes = Recipe.includes(:recipeFoods).where(public: true).order('created_at DESC')
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
    @publics = Recipe.where(public: true).order('created_at DESC').with_attached_image
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def new
    @recipe_food = RecipeFood.new
    @recipe_food_ids = RecipeFood.all.where(recipe_id: params[:recipe_id]).pluck(:food_id)
    @foods = Food.all.where(user_id: current_user.id).where.not(id: @recipe_food_ids).order(name: :asc)
    @recipe = Recipe.where(recipe_id: params[:recipe_id])
  end

  def create
    @recipe_food = RecipeFood.new
    @recipe_food_ids = RecipeFood.all.where(recipe_id: params[:recipe_id]).pluck(:food_id)
    @foods = Food.all.where(user_id: current_user.id).where.not(id: @recipe_food_ids).order(name: :asc)
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.recipe_id = params[:recipe_id]
    if recipe_food.save
      flash[:success] = 'Food was successfully added to recipe.'
    else
      flash[:danger] = 'Food was not added to recipe because <ul class="error-list">'
      recipe_food.errors.full_messages.each do |msg|
        flash[:danger] += "<li>#{msg}</li>"
      end
      flash[:danger] += '</ul>'
    end
    redirect_to new_recipe_recipe_food_path(params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all.where(user_id: current_user).order(created_at: :desc).with_attached_image
  end

  def show
    data = Recipe.where(id: params[:id]).with_attached_image
    @recipe = data[0]
    @recipe_foods = Food.all.joins('INNER JOIN recipe_foods ON foods.id = recipe_foods.food_id')
      .order(created_at: :desc).select('foods.*, recipe_foods.quantity, recipe_foods.id as recipe_foods_id')
      .where(recipe_foods: { recipe_id: params[:id] }).with_attached_image
    return unless current_user
  end

  def new
    @user = current_user
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:success] = 'Recipe created successfully'
      redirect_to recipes_path
    else
      flash.now[:danger] = 'Recipe was not created because <ul class="error-list">'
      @recipe.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
      render :new
    end
  end

  def update
    Recipe.find(params[:id]).update(public: params[:recipe][:public])
  end

  private

  def recipe_params
    params.permit(:name, :preparation_time, :cooking_time, :description, :image, :user_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'User was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food.helper.rb
module FoodHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/recipe.helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foods/_form.html.erb
<div class="container food-form">

<%= form_with(model: food) do |form| %>
  <div class="card form">
  <div class="card-body">
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <div>
      <%= form.text_field :name, autofocus: true, class: "form-control", required: true %>
    </div>
  </div>

  <div>
    <%= form.label :measurement_unit, class: "form-label" %>
    <div>
      <%= form.text_field :measurement_unit, autofocus: true, class: "form-control", required: true %>
    </div>
  </div>

  <div>
    <%= form.label :price, class: "form-label" %>
    <div>
      <%= form.number_field :price, autofocus: true, class: "form-control", required: true, min: 1 %>
    </div>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary btn-floating mx-1 food-btn" %>
  </div>
</div>
</div>
<% end %> 

app/views/foods/index.html.erb
<h5 class="card-title">List of foods</h5>
<div class="table-responsive">
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td>
            <% if food.image.present? %>
              <%= image_tag food.image, class: "bio-photo" %>
            <% else %>
              <%= image_tag "https://nuwaay.com/wp-content/uploads/2022/01/default_256.png", class: "bio-photo" %>
            <% end %>
          </td>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td>
            <%= button_to "Delete", food_path(food.id), method: :delete, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</table>
</div>

app/views/foods/new.html.erb
<div class="row">
    <div class="mb-3 col-md-8 offset-md-2">
    <div class="row g-0">
        <div class="col-md-12 background shadow">
            <div class="card-body transbox">
                <h5 class="card-title">Add Food to your store</h5>
                <%= form_with model: @food, url: foods_path, local: true do |form| %>
                    <div class="form-floating mb-3">
                        <%= form.file_field :image, class: 'form-control' %>
                        <%= form.label :image, 'Image if any', class: 'p-2' %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= form.text_field :name, class: "form-control", required: true %>
                        <%= form.label :name, "Name of Food *" %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= form.select :measurement_unit, [['grams', 'g'], ['kilograms', 'kg'], ['milligrams', 'ml'], ['liter', 'l'], ['ounces', 'oz'], ['pound', 'lb'], ['cup', 'cup'], ['pint', 'pint'], ['quart', 'quart'], ['gallon', 'gallon']], {:include_blank => "-", :required => true}, {:class => 'form-control'} %>
                        <%= form.label :measurement_unit, "Choose measuring unit *" %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= form.number_field :price, class: "form-control", required: true %>
                        <%= form.label :price, "Unit price($) *" %>
                    </div>
                    <div class="form-group mt-3">
                        <%= form.submit '🥣 Add Food', class: "btn", style: "background-color: var(--primary-color); color: var(--white);", data: {disable_with: "Loading..."} %>
                    </div>
                <% end %>
                <p class="card-text"><small class="text-muted">updating as <%= current_user.name %></small></p>
            </div>
        </div>
    </div>
    </div>
</div>

app/views/general_shopping_list/index.html.erb
<div class="container">
  <h1 class="text-center mt-4">Shopping List</h1>
  <div class="d-flex justify-content-between m-5">
    <h3>Amount of food items to buy: <%= @food_amount %></h3>
    <h3>Total value of food needed: $<%= @total_price %></h3>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
        </tr>
    </thead>
    <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <% recipe_food.each do |ingredients| %>
      <tr>
        <th scope="row"><%= ingredients.food.name %> </th>
        <td><%= ingredients.quantity %><%= ingredients.food.measurement_unit %> </td>
        <td>$ <%= ingredients.food.price * ingredients.quantity %></td>
      </tr>
      <% end %>
      <%end %>
   </tbody>
  </table>
</div>

app/views/publics/index.html.erb
<div class="row">
<h1 class="text-center">Public Recipes</h1>
<% @publics.each do |public|%>
<div class="col-md-3">
<div class="shadow-lg m-3 bg-white public-card">
    <% if public.image.present? %>
       <%= image_tag public.image, class: "card-img-top" %>
    <% else %>
        <%= image_tag "no-food-image.jpeg", class: "card-img-top" %>
    <% end %>
    <div class="card-body">
        <h5 class="card-title py-3"><%= public.name %></h5>
        <p class="card-text"><%= truncate(public.description, length: 90, omission: '...') %></p>
        <a href="/recipes/<%= public.id %>" class="btn", style= "background-color: var(--primary-color); color: var(--white)">View Recipe</a>
    </div>
</div>
</div>
<% end %>
</div>

app/views/recipe_food/index.html.erb
<h1>RecipeFood#index</h1>
<p>Find me in app/views/recipe_food/index.html.erb</p>

app/views/recipe_foods/new.html.erb
<%= render partial: "shared/recipe_food_form", locals: {recipe: @recipe, foods: @foods, method: 'post', recipe_food: @recipe_food, type: 'new', url: recipe_foods_path} %>

app/views/recipes/index.html.erb
<h5 class="mb-2">Your Recipies (<%= @recipes.length %>)</h5>
<hr />
<div class="row">
    <% @recipes.each do |recipe| %>
     <%= render partial: "shared/recipe_display", locals: {recipe: recipe} %>
    <% end %>
</div>

app/views/recipes/my_recipes.html.erb
<div class="recepie_area plus_padding">
  <div class="container">
  <div class="text-center mb-4">
    <%= link_to "Add New Recipe", new_recipe_path, class: "line_btn" if user_signed_in? %>
  </div>
    <% if @recipes.blank? %>
      <h2>There are no recipes, check back later</h2>
    <% else %>
      <div class="row">
        <% @recipes.each do |recipe|%>
        <div class="col-xl-4 col-lg-4 col-md-6">
          <div class="single_recepie text-center">
            <div class="recepie_thumb">
              <img src="https://res.cloudinary.com/optprime/image/upload/v1658841781/community_blog/recpie_3_q2bdjn.png" alt="Recipe">
              </div>
              <h3><%= recipe.name %></h3>
              <p>Preparation Time: <%= recipe.preparation_time %> hour</p>
              <p>Cooking Time: <%= recipe.cooking_time %> hour</p>
              <%= link_to "View Recipe", recipe_path(recipe.id), class: "line_btn" %>
            </div>
          </div>
        <%end%>
      <%end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="row  container-fluid">
    <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
        <div class="card-body">
        <h5 class="card-title">😊 Create a new recipe!!</h5>
        <p class="card-text"> Would'nt it be nice to store a recipe of your favourite food? Go ahead!</p>
            <%= form_with model: @recipe, url: recipes_path do |f| %>
                <%= f.hidden_field :user_id, value: @user.id %>
                <div class="mb-3">
                    <%= f.file_field :image, class: 'form-control' %>
                    <%= f.label :image, 'Choose an image that would appear as banner for recipe', class: 'mb-2' %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_field :name, class: 'form-control', required: true %>
                    <%= f.label :name, "Recipe Name*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_field :preparation_time, class: 'form-control', required: true %>
                    <%= f.label :preparation_time, "Preparation Time in mins*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_field :cooking_time, class: 'form-control', required: true %>
                    <%= f.label :cooking_time, "Cooking Time in mins*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_area :description, class: 'form-control' %>
                    <%= f.label :description, "Description" %>
                </div>
                
                <div class="form-group mt-3">
                    <%= f.submit '🥣 Create Recipe', class: "btn", style: "background-color: var(--primary-color); color: var(--white);", data: {disable_with: "Loading..."} %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="recepie_area plus_padding">
  <div class="container">
  <div class="text-center mb-4">
    <%= link_to "Add New Recipe", new_recipe_path, class: "line_btn" if user_signed_in? %>
  </div>
    <% if @recipes.blank? %>
      <h2>There are no recipes, check back later</h2>
    <% else %>
      <div class="row">
        <% @recipes.each do |recipe|%>
        <div class="col-xl-4 col-lg-4 col-md-6">
          <div class="single_recepie text-center">
            <div class="recepie_thumb">
              <img src="https://res.cloudinary.com/optprime/image/upload/v1658841781/community_blog/recpie_3_q2bdjn.png" alt="Recipe">
              </div>
              <h3><%= recipe.name %></h3>
              <p>Preparation Time: <%= recipe.preparation_time %> hour</p>
              <p>Cooking Time: <%= recipe.cooking_time %> hour</p>
              <%= link_to "View Recipe", recipe_path(recipe.id), class: "line_btn" %>
            </div>
          </div>
        <%end%>
      <%end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<%= link_to ' << Public Recipes', publics_path, class: "btn btn-outline mb-2"%> 
<%= link_to ' << Recipes', recipes_path, class: "btn btn-outline mb-2" if current_user %> 
<div class="container">
    <div class="card text-center ">
        <h4 class="card-header" style="background: var(--primary-color); color: var(--white)">
          <%= @recipe.name %>
        </h4>
        <div class="row mx-5 mt-2">
          <div class="col-md-9">
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Preparation time: <%= @recipe.preparation_time %></p>
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Cooking time: <%= @recipe.cooking_time %></p> 
          </div>
          <% if current_user && @recipe.user_id == current_user.id %>
            <div class="col-md-3">
                <%= form_with model: @recipe, url: recipe_path(@recipe.id), method: :patch, local: true do |form| %>
                  <div class="form-switch">
                      <%= form.check_box :public, class: "form-check-input", onchange: 'this.form.submit()' %>
                      <%= form.label :public, 'public', class: "form-check-label", checked: @recipe.public %> <br />
                  </div>
                <% end %>
            </div>
          <% end %>
        </div>
    </div>
    <% if current_user && @recipe.user_id == current_user.id %>
      <div class="mt-4">
          <button type="button"class='btn btn-outline-primary mb-2 flex-start' data-bs-toggle="modal" data-bs-target="#listBackdrop">
            <i class="fa fa-shopping-basket" aria-hidden="true"></i> Generate shopping list
          </button>
          <span style="float: right">
            <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add food ingredient'.html_safe, new_recipe_food_path(@recipe.id), class: "btn btn-outline-success mb-2 flex-end" %> 
          </span>
      </div>
    <% end %>
    <table class="table table-striped text-center">
    <thead>
      <tr>
        <th class="text-center">#</th>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <% if current_user && @recipe.user_id == current_user.id %>
          <th>Action</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
          <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td>
              <% if recipe_food.image.present? %>
                <%= image_tag recipe_food.image, class: "bio-photo" %>
              <% else %>
                <%= image_tag "no-food-image.png", class: "bio-photo" %>
              <% end %>
          </td>
          <td><%= recipe_food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td>$<%= recipe_food.price * recipe_food.quantity %></td>
          <% if current_user && @recipe.user_id == current_user.id %>
            <td>
              <a href="<%= edit_recipe_recipe_food_path(@recipe.id, recipe_food.recipe_foods_id) %>" class='btn btn-outline-primary'>
                <i class="fa fa-pencil" aria-hidden="true"></i>  
                Modify
              </a>
              <a href="<%= recipe_recipe_food_path(@recipe.id, recipe_food.recipe_foods_id) %>" data-confirm="Delete <%= recipe_food.name %> from this recipe?" data-method="delete" class='btn btn-outline-danger'>
                <i class="fa fa-trash" aria-hidden="true"></i>
                Delete
              </a>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/user/index.html.erb
<h1>Welome <%=@user.name%></h1>
<%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete } %>