config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  resources :foods
  resources :publics, only: [:index]
  resources :recipe_foods

  root "publics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 100 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :name
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :recipe_id, presence: true
  validates :food_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success, :messages, :notice, :alert
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :password, :password_confirmation, :email, :image)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :password_confirmation, :email, :current_password, :image)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc).with_attached_image
  end

  def new
    @food = Food.new
  end

  def create
    new_food = Food.new(food_params)
    new_food.user_id = current_user.id

    if new_food.save
      flash.now[:success] = 'Food was successfully created.'
      redirect_to foods_path
    else
      flash.now[:danger] = 'Food was not created because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
      render :new
    end
  end

  def destroy
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc).with_attached_image

    food_to_delete = Food.find(params[:id])
    if food_to_delete.destroy
      flash.now[:success] = 'Food was successfully deleted.'
    else
      flash.now[:danger] = 'Food was not deleted because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
    end
    render :index
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :image)
  end

  private :food_params
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
  def index
    @recipes = Recipe.includes(:recipeFoods).where(public: true).order('created_at DESC')
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
    @publics = Recipe.where(public: true).order('created_at DESC').with_attached_image
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def new
    @recipe_food = RecipeFood.new
    @recipe_food_ids = RecipeFood.all.where(recipe_id: params[:recipe_id]).pluck(:food_id)
    @foods = Food.all.where(user_id: current_user.id).where.not(id: @recipe_food_ids).order(name: :asc)
    @recipe = Recipe.where(recipe_id: params[:recipe_id])
  end

  def create
    @recipe_food = RecipeFood.new
    @recipe_food_ids = RecipeFood.all.where(recipe_id: params[:recipe_id]).pluck(:food_id)
    @foods = Food.all.where(user_id: current_user.id).where.not(id: @recipe_food_ids).order(name: :asc)
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.recipe_id = params[:recipe_id]
    if recipe_food.save
      flash[:success] = 'Food was successfully added to recipe.'
    else
      flash[:danger] = 'Food was not added to recipe because <ul class="error-list">'
      recipe_food.errors.full_messages.each do |msg|
        flash[:danger] += "<li>#{msg}</li>"
      end
      flash[:danger] += '</ul>'
    end
    redirect_to new_recipe_recipe_food_path(params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all.where(user_id: current_user).order(created_at: :desc).with_attached_image
  end

  def show
    data = Recipe.where(id: params[:id]).with_attached_image
    @recipe = data[0]
    @recipe_foods = Food.all.joins('INNER JOIN recipe_foods ON foods.id = recipe_foods.food_id')
      .order(created_at: :desc).select('foods.*, recipe_foods.quantity, recipe_foods.id as recipe_foods_id')
      .where(recipe_foods: { recipe_id: params[:id] }).with_attached_image
    return unless current_user
  end

  def new
    @user = current_user
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:success] = 'Recipe created successfully'
      redirect_to recipes_path
    else
      flash.now[:danger] = 'Recipe was not created because <ul class="error-list">'
      @recipe.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
      render :new
    end
  end

  def update
    Recipe.find(params[:id]).update(public: params[:recipe][:public])
  end

  private

  def recipe_params
    params.permit(:name, :preparation_time, :cooking_time, :description, :image, :user_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'User was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food.helper.rb
module FoodHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/recipe.helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_navbar.html.erb
<nav class="flex px-8 py-4 justify-between items-center gap-12 border-b-2 border-sky-700 bg-sky-300">

  <div class="left-side flex gap-3 items-center w-fit">
    <%=bootstrap_form_with url: root_path, method: :get do %>
      <button class="text-sky-600">Home</button>
    <% end %>
    <% if current_user.present? %>
      <%=bootstrap_form_with url: recipes_path, method: :get do %>
        <button class="text-sky-600">Recipes</button>
      <% end %>
      <%=bootstrap_form_with url: foods_path, method: :get do %>
        <button class="text-sky-600">Foods</button>
      <% end %>
      <%=bootstrap_form_with url: inventories_path, method: :get do %>
        <button class="text-sky-600">Inventories</button>
      <% end %>
    <% end %>
  </div>
  <div class="righ-side flex gap-3 items-center w-fit">
    <% unless current_user.present? %>
    <%=bootstrap_form_with model: User.new, url: new_user_session_path, method: :get do %>
      <button class="text-sky-600">Sign in</button>
    <% end %>
    <%=bootstrap_form_with model: User.new, url: new_user_registration_path, method: :get do %>
      <button class="text-sky-600">Sign up</button>
    <% end %>
  <% end %>
  <% if current_user.present? %>
    <span class="text-lg text-blue-800">
      <%= current_user.email %>
    </span>
    <%=bootstrap_form_with model: User.new, url: destroy_user_session_path, method: :delete do %> 
      <button class="text-red-600">Sign out</button>
    <% end %>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg mb-3" style="background-color: var(--accent-color)">
        <div class="container">
          <%= link_to "RecipeBook", root_path, :"data-turbolinks" => false, class: "navbar-brand display-6" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">    
              <li class="nav-item">
                <%= link_to "Public Recipes", publics_path, :"data-turbolinks" => false, class: "nav-link" %>
              </li>
              <% if current_user %> 
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo="false">
                    Recipe
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to "My Recipes", recipes_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Add Recipe", new_recipe_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo="false">
                    Foods
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to "My Foods", foods_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Add Food", new_food_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% end %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  My Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <% if current_user %>
                    <li> <%= link_to "My Profile", edit_user_registration_path, :"data-turbolinks" => false, class: "nav-link" %></li>
                    <li><%= button_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Sign Out'.html_safe, destroy_user_session_path, method: :delete, :"data-turbolinks" => false, class: "nav-link link-btn" %></li>
                  <% else %>
                    <li><%= link_to '<i class="fa fa-sign-in" aria-hidden="true"></i> Sign In'.html_safe, new_user_session_path, :"data-turbolinks" => false, class: "nav-link" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Become a member", new_user_registration_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <div class="d-flex flex-column">
              <div class="d-flex flex-row align-items-center">
                  
                  <div class="d-flex flex-column user-details">
                    <span><%= current_user.name if current_user %></span>
                    <span><%= current_user.email if current_user %></span>
                  </div>
              </div> 
            </div>
          </div>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ingredients.html.erb
<div class="mb-4">
  <div class="d-flex flex-row justify-content-between">
    <div>
      <% if user_signed_in? && @recipe.user == current_user %>
        <%= link_to "Generate Shopping List", general_shopping_list_index_path, class: 'line_btn' %>
      <% end %>
    </div>
    <div>
      <% if recipe.user == current_user  %>
        <%= form_with model: @RecipeFood, url: recipe_recipe_foods_path(recipe), class: 'form-inline', method: :post do |form| %>
          <div class="form-group mb-2">
            <%= form.number_field :quantity, placeholder: 'Quantity', min: 0, class: "form-control" %>
          </div>
          <div class="form-group mx-sm-3 mb-2">
            <%= form.collection_select :food_id, recipe.user.foods, :id, :name, class: "form-control" %>
          </div>
          <%= form.submit 'Add', class: 'btn btn-primary mb-2' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if recipe.foods.blank? %>
    <h4 class="text-center">No foods available!</h4>
  <% else %>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% recipe.recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= "#{recipe_food.quantity} #{recipe_food.food.measurement_unit}" %></td>
          <td><%= "$ #{recipe_food.quantity * recipe_food.food.price}" %></td>
          <td>
            <% if recipe_food.recipe.user == current_user %>
            <%= button_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: 'btn btn-danger' %> 
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
</div>

app/views/shared/_recipe_details.html.erb
    <div class="recepie_details_area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-6 col-md-6">
                    <div class="recepies_thumb">
                        <img src="https://res.cloudinary.com/optprime/image/upload/v1658841777/community_blog/recepie_details_hzgxw3.png" alt="Recipe photo">
                    </div>
                </div>
                <div class="col-xl-6 col-md-6">
                    <div class="recepies_info">
                        <div class="d-flex justify-content-end mb-4">
                        <span class="pr-4">Public</span>
                         <div class="form-check form-switch text-center pl-4">
                         <% if current_user.id == @recipe.user.id %> 
                            <%= button_to recipe_path(@recipe.id), :method => :patch do %>
                                <% if @recipe.public %>
                                    <i class="fa-solid fa-toggle-on" style="font-size:24px;color:green"></i>
                                <% else %>
                                    <i class="fa-solid fa-toggle-off" style="font-size:24px;color:green"></i>
                                <% end %>
                            <% end %>
                        <% end %>
                        </div>
                        </div>
                        <h2><%= @recipe.name %></h2>
                        <div class="resepies_details">
                            <ul>
                                <li><p><strong>Preparation Time</strong> : <%= @recipe.preparation_time %> hours </p></li>
                                <li><p><strong>Cooking Time</strong> : <%= @recipe.cooking_time %> hours </p></li>
                            </ul>
                        </div>
                        <% if user_signed_in? && @recipe.user == current_user %>
                            <%= button_to "Delete Recipe", recipe_path(@recipe.id), method: :delete, class: "line_btn" %>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                <h2>Steps to follow</h2>
                    <div class="recepies_text">
                        <p><%= @recipe.description %></p>
                        <h3 class="py-4 text-center">Add recipe ingredients</h3>
                    </div>
                </div>
             <%= render partial: "shared/ingredients", locals: { recipe: @recipe } %>   
            </div>
        </div>
    </div>

app/views/shared/_recipe_display.html.erb
<div class="col-md-4 offset-md-1 shadow inventory-card mb-3">
<div class="row g-0">
    <div class="col-md-3">
        <% if recipe.image.present? %>
            <%= image_tag recipe.image, class: "img-fluid" %>
        <% else %>
            <%= image_tag "no-food-image.jpeg", class: "img-fluid" %>
        <% end %>
    </div>
    <div class="col-md-9">
    <div class="card-body">
        <h5 class="card-title"><%= recipe.name %></h5>
        <p class="card-text"><%= recipe.description.length < 54 ? recipe.description : truncate(recipe.description, length: 100, omission: '...') %></p>
        <p class="card-text">
            <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i> Show'.html_safe, recipe_path(recipe.id), class: 'btn btn-outline-info' %>
            <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, recipe_path(recipe.id), method: :delete, data: { confirm: "Delete recipe #{recipe.name}?" }, class: 'btn btn-outline-danger' %>
        </p>
        <% if current_user %>
            <small class="text-muted" style="float:right"><%= recipe.public ? '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe : '' %></small>
        <% end %>
    </div>
    </div>
</div>
</div>

app/views/shared/_recipe_food_form.html.erb
<div class="row">
    <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
        <div class="card-body">
        <% if type != 'edit' %>
            <h5>Add Ingredient to <%= recipe.name %></h5>
        <% else %>
            <h6>Updating <i> <%= recipe_food.food.name %> </i> in <%= recipe.name %></h6>
        <% end %>
        <%= form_with model: recipe_food, url: url, method: method, local: true do |form| %>
            <% if type != 'edit' %>
                <div class="form-floating mb-3">
                    <%= form.select :food_id, foods.map { |food| [food.name, food.id] }, {:include_blank => "-", :required => true}, {:class => 'form-control'} %>
                    <%= form.label :food_id, "Choose food from the list to add *" %>
                </div>
            <% end %>
            <div class="form-floating mb-3">
                <%= form.number_field :quantity, class: "form-control", required: true %>
                <%= form.label :quantity, "Quantity *" %>
            </div>
            <% if type != 'edit' %>
                <div class="form-group mt-3">
                    <%= form.submit 'Add Ingredient to recipe', class: "btn btn-primary", data: {disable_with: "Loading..."} %>
                </div>
            <% else %>
                <div class="form-group mt-3">
                    <%= form.submit "Update #{recipe_food.food.name}", class: "btn btn-primary", data: {disable_with: "Loading..."} %>
                </div>    
            <% end %>
        <% end %>
        <p class="card-text"><small class="text-muted">Updating as <%= current_user.name %></small></p>
        </div>
  </div>
</div>

app/views/shared/_recipes_list.html.erb
<div class="recepie_area plus_padding">
  <div class="container">
  <div class="text-center mb-4">
    <%= link_to "Add New Recipe", new_recipe_path, class: "line_btn" if user_signed_in? %>
  </div>
    <% if @recipes.blank? %>
      <h2>There are no recipes, check back later</h2>
    <% else %>
      <div class="row">
        <% @recipes.each do |recipe|%>
        <div class="col-xl-4 col-lg-4 col-md-6">
          <div class="single_recepie text-center">
            <div class="recepie_thumb">
              <img src="https://res.cloudinary.com/optprime/image/upload/v1658841781/community_blog/recpie_3_q2bdjn.png" alt="Recipe">
              </div>
              <h3><%= recipe.name %></h3>
              <p>Preparation Time: <%= recipe.preparation_time %> hour</p>
              <p>Cooking Time: <%= recipe.cooking_time %> hour</p>
              <%= link_to "View Recipe", recipe_path(recipe.id), class: "line_btn" %>
            </div>
          </div>
        <%end%>
      <%end %>
    </div>
  </div>
</div>

app/views/shared/_shopping_list.html.erb
Testing